apiVersion: skaffold/v2alpha3
kind: Config 
deploy: 
  kubectl:
    manifests: 
      - ./deployments/*
build: 
  local: 
    push: true
  artifacts: 
    - image: adminondemand.azurecr.io/authentication
      context: ../auth
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: 'src/**/*.ts'
            dest: .
    - image: adminondemand.azurecr.io/frontend
      context: ../client
      docker: 
        dockerfile: Dockerfile
      sync: 
        manual: 
          - src: '*'
            dest: .