apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: 'true'
spec:
  rules:
    - host: adminondemand.ml
      http: 
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend: 
              service:
                name: authentication-cip
                port:
                  number: 3000