apiVersion: apps/v1
kind: Deployment
metadata: 
  name: authentication
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: authentication
  template: 
    metadata: 
      labels: 
        app: authentication
    spec: 
      containers: 
        - name: authentication
          image: adminregistry.azurecr.io/authentication
          imagePullPolicy: Always
          env: 
            - name: JWT_KEY
              valueFrom: 
                secretKeyRef: 
                  name: jwt-secret
                  key: JWT_KEY
          ports: 
            - containerPort: 3000
          volumeMounts: 
          - name: adminondemand-cert
            mountPath: /run/adminondemand
            readOnly: true
      volumes: 
      - name: adminondemand-cert
        secret: 
          secretName: tls
          optional: false
      imagePullSecrets:
      - name: registry-secret
--- 
apiVersion: v1
kind: Service
metadata: 
  name: authentication-cip
spec: 
  selector: 
    app: authentication
  type: ClusterIP
  ports:
    - name: authentication
      port: 3000
      targetPort: 3000
      protocol: TCP